benchmarks:
  stable-diffusion-xl:
    "FID_SCORE": 23.01085758
    "CLIP_SCORE": 31.68631873
    "FID_SCORE_MAX": 23.95007626
    "CLIP_SCORE_MAX": 31.81331801
scenarios:
  sd-xl-fp8:
    dataset: coco-2014
    code_dir: stable-diffusion-xl
    benchmark: stable-diffusion-xl
    command: QUANT_CONFIG=tools/quantize/quant_config.json QUANT_CONFIG_2=tools/quantize/quant_config_bmm.json python3 main.py --dataset "coco-1024" --dataset-path coco2014 --profile stable-diffusion-xl-pytorch --dtype bf16 --output build/logs --user_conf configs/user.conf --hpus 8 --max-batchsize 4 --quantize --model-path /mnt/weka/data/mlperf_inference/stable-diffusion-xl/stable_diffusion_fp32/
    precision: fp8
    batch_size: 4
    init_setup: cd tools; ./download-coco-2014.sh -n 1; cd -;
